Add sanity checks/regression tests for session management
I hoped that these unit tests would reproduce an error, which
prevents some information from being fetched the mobile application
on first load. The current reflection is always displayed but the
case and/or the tips tend to be missing (issue #6). The server log
contained the following for an instance of this problem:

IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '0K3KdtHs7sy4ZZUpXL5ox3VCFXzomr' for key 'PRIMARY'") [SQL: u'INSERT INTO session (token, expires, payload) VALUES (%s, %s, %s)'] [parameters: ('0K3KdtHs7sy4ZZUpXL5ox3VCFXzomr', datetime.datetime(2016, 11, 4, 10, 12, 17, 576319), '\x80\x02}q\x01(U\x05tokenq\x02X\x1e\x00\x00\x000K3KdtHs7sy4ZZUpXL5ox3VCFXzomrq\x03U\x07taintedq\x04\x88U\n_permanentq\x05\x88u.')]

Which indicates that the information was not fetched because the
server returned a 5xx response, which it did because it considered
the session invalid. It tried to store the invalid session as
"tainted" and then stumbled across a duplicate, because the token was
actually valid and pre-existing.

The tests in this commit do not reproduce the problem. However, while
writing this, I realise the problem is caused by a race condition.
This is something to fix in the next commit.